version: '3'

services:
  nginx:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  helloworld:
    image: serhatdzn/html-image:v1
    ports:
        - "81:80"
    environment:
      - VIRTUAL_HOST=serhatdzn.com
    deploy:
      placement:
        constraints:
        - node.hostname==docker-instance-3

  byeworld:
    image: serhatdzn/html-image:v2
    ports:
        - "82:80"
    environment:
      - VIRTUAL_HOST=api.serhatdzn.com
    deploy:
      placement:
        constraints:
        - node.hostname==docker-instance-2

  
